<!--
  error.tpl

  3EProfiler (tm) template file.
  Copyright (C) 2003 Michael J. Eggertson.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

  **

  Defines the look of basic, uncustomized system error pages generated by
  3EProfiler.
-->
<?php global $body; ?>

<h1>Error!</h1>
<p>
  An internal error has ocurred while trying to perform your request,
  details of the error are listed below:
</p>
<p class="code">
  <?php echo $body; ?>
</p>
<p>
  Use your browser's <a href="javascript:history.back(1);">back</a> button
  to go back to the previous page. If this error persists, you may wich to
  contact the <a href="<?echo getUriWebmaster(); ?>">site operator</a>.
</p>
