// ogl/skills.js

// Skill information used by 3EProfiler that was released by WotC under
// the Open Gaming License (OGL). This file however, is not released under
// the OGL (see above).

var abilityKeys = [
  , // zero index undefined.
  'Str',
  'Dex',
  'Con',
  'Int',
  'Wis',
  'Cha'
];

// Defines the key abilities for each set of core skills.
var skillKeys = {
  'appraise': 4,
  'balance': 2,
  'bluff': 6,
  'climb': 1,
  'concentration': 3,
  'craft': 4,
  'decipher script': 4,
  'diplomacy': 6,
  'disable device': 4,
  'disguise': 6,
  'escape artist': 2,
  'forgery': 4,
  'gather information': 6,
  'handle animal': 6,
  'heal': 5,
  'hide': 2,
  'intimidate': 6,
  'jump': 1,
  'knowledge': 4,
  'listen': 5,
  'move silently': 2,
  'open lock': 2,
  'perform': 6,
  'profession': 5,
  'ride': 2,
  'search': 4,
  'sense motive': 5,
  'sleight of hand': 2,
  'spellcraft': 4,
  'spot': 5,
  'survival': 5,
  'swim': 1,
  'tumble': 2,
  'use magic device': 6,
  'use rope': 2
};

// Defines which skills are class skills for each core class.
var classSkills = {
                           // Bbn Brd Clr Drd Ftr Mnk Pal Rgr Rog Sor Wiz
  'Appraise':                 [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Balance':                  [0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Bluff':                    [0,  1,  0,  0,  0,  0,  0,  0,  1,  1,  0 ],
  'Climb':                    [1,  1,  0,  0,  1,  1,  0,  1,  1,  0,  0 ],
  'Concentration':            [0,  1,  1,  1,  0,  1,  1,  1,  0,  1,  1 ],
  'Craft':                    [1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1 ],
  'Decipher Script':          [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  1 ],
  'Diplomacy':                [0,  1,  1,  1,  0,  1,  1,  0,  1,  0,  0 ],
  'Disable Device':           [0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Disguise':                 [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Escape Artist':            [0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Forgery':                  [0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Gather Information':       [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Handle Animal':            [1,  0,  0,  1,  1,  0,  1,  1,  0,  0,  0 ],
  'Heal':                     [0,  0,  1,  1,  0,  0,  1,  1,  0,  0,  0 ],
  'Hide':                     [0,  1,  0,  0,  0,  1,  0,  1,  1,  0,  0 ],
  'Intimidate':               [1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0 ],
  'Jump':                     [1,  1,  0,  0,  1,  1,  0,  1,  1,  0,  0 ],
  'Knowledge: Arcana':        [0,  1,  1,  0,  0,  1,  0,  0,  0,  1,  1 ],
  'Knowledge: Architecture':  [0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1 ],
  'Knowledge: Dungeoneering': [0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  1 ],
  'Knowledge: Geography':     [0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  1 ],
  'Knowledge: History':       [0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1 ],
  'Knowledge: Local':         [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  1 ],
  'Knowledge: Nature':        [0,  1,  0,  1,  0,  0,  0,  1,  0,  0,  1 ],
  'Knowledge: Nobility':      [0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  1 ],
  'Knowledge: Religion':      [0,  1,  1,  0,  0,  1,  1,  0,  0,  0,  1 ],
  'Knowledge: The Planes':    [0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1 ],
  'Listen':                   [1,  1,  0,  1,  0,  1,  0,  1,  1,  0,  0 ],
  'Move Silently':            [0,  1,  0,  0,  0,  1,  0,  1,  1,  0,  0 ],
  'Open Lock':                [0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Perform':                  [0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Profession':               [0,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1 ],
  'Ride':                     [1,  0,  0,  1,  1,  0,  1,  1,  0,  0,  0 ],
  'Search':                   [0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0 ],
  'Sense Motive':             [0,  1,  0,  0,  0,  1,  1,  0,  1,  0,  0 ],
  'Sleight of Hand':          [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Speak Language':           [0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  'Spellcraft':               [0,  1,  1,  1,  0,  0,  0,  0,  0,  1,  1 ],
  'Spot':                     [0,  0,  0,  1,  0,  1,  0,  1,  1,  0,  0 ],
  'Survival':                 [1,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0 ],
  'Swim':                     [1,  1,  0,  1,  1,  1,  0,  1,  1,  0,  0 ],
  'Tumble':                   [0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Use Magic Device':         [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Use Rope':                 [0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0 ]
};


var skillAttributes = {
                           // Unskilled use   Armor check
  'appraise':                 [  true,          false        ],
  'balance':                  [  true,          true         ],
  'bluff':                    [  true,          false        ],
  'climb':                    [  true,          true         ],
  'concentration':            [  true,          false        ],
  'craft':                    [  true,          false        ],
  'decipher script':          [  false,         false        ],
  'diplomacy':                [  true,          false        ],
  'disable device':           [  false,         false        ],
  'disguise':                 [  true,          false        ],
  'escape artist':            [  true,          true         ],
  'forgery':                  [  true,          false        ],
  'gather information':       [  true,          false        ],
  'handle animal':            [  false,         false        ],
  'heal':                     [  true,          false        ],
  'hide':                     [  true,          true         ],
  'intimidate':               [  true,          false        ],
  'jump':                     [  true,          true         ],
  'knowledge:':               [  false,         false        ],
  'listen':                   [  true,          false        ],
  'move silently':            [  true,          true         ],
  'open lock':                [  false,         false        ],
  'perform':                  [  true,          false        ],
  'profession':               [  true,          false        ],
  'ride':                     [  true,          false        ],
  'search':                   [  true,          false        ],
  'sense motive':             [  true,          false        ],
  'sleight of hand':          [  false,         true         ],
  'speak language':           [  false,         false        ],
  'spellcraft':               [  false,         false        ],
  'spot':                     [  true,          false        ],
  'survival':                 [  true,          false        ],
  'swim':                     [  true,          true         ],
  'tumble':                   [  false,         true         ],
  'use magic device':         [  false,         false        ],
  'use rope':                 [  true,          false        ]
};

// Now transform the classSkill object to contain a bitset rather than an array.
for (var skill in classSkills)
{
  var cc_code = 0;
  for (var i = 0; i < classSkills[skill].length; i++)
    cc_code = (cc_code << 1) | classSkills[skill][i];
  classSkills[skill] = cc_code;
}

var baseHelpURL = "http://www.d20srd.org/srd/"

// Defines the URL that points to help for each skill, feat, ability, etc.
// NOTE: in cases where there is some overlap in names--like "armor proficiency"
// and "armor proficiency (light)"--the more specific one MUST come first.
var skillsHelpURL = {

  // Skills
  'appraise':                baseHelpURL + "skills/appraise.htm",
  'balance':             baseHelpURL + "skills/balance.htm",
  'bluff':                   baseHelpURL + "skills/bluff.htm",
  'climb':                   baseHelpURL + "skills/climb.htm",
  'concentration':       baseHelpURL + "skills/concentration.htm",
  //craft moved down a bit to support craft feats
  //'craft':                   baseHelpURL + "skills/craft.htm",
  'decipher script':         baseHelpURL + "skills/decipherScript.htm",
  'diplomacy':               baseHelpURL + "skills/diplomacy.htm",
  'disable device':      baseHelpURL + "skills/disableDevice.htm",
  'disguise':                baseHelpURL + "skills/disguise.htm",
  'escape artist':       baseHelpURL + "skills/escapeArtist.htm",
  'forgery':                 baseHelpURL + "skills/forgery.htm",
  'gather information':  baseHelpURL + "skills/gatherInformation.htm",
  'handle animal':       baseHelpURL + "skills/handleAnimal.htm",
  'heal':                    baseHelpURL + "skills/heal.htm",
  'hide':                    baseHelpURL + "skills/hide.htm",
  'intimidate':          baseHelpURL + "skills/intimidate.htm",
  'jump':                    baseHelpURL + "skills/jump.htm",
  'knowledge':               baseHelpURL + "skills/knowledge.htm",
  'listen':                  baseHelpURL + "skills/listen.htm",
  'move silently':       baseHelpURL + "skills/moveSilently.htm",
  'open lock':               baseHelpURL + "skills/openLock.htm",
  'perform':                 baseHelpURL + "skills/perform.htm",
  'profession':          baseHelpURL + "skills/profession.htm",
  'ride':                    baseHelpURL + "skills/ride.htm",
  'search':                  baseHelpURL + "skills/search.htm",
  'sense motive':            baseHelpURL + "skills/senseMotive.htm",
  'sleight of hand':         baseHelpURL + "skills/sleightOfHand.htm",
  'speak language':      baseHelpURL + "skills/speakLanguage.htm",
  'spellcraft':          baseHelpURL + "skills/spellcraft.htm",
  'spot':                    baseHelpURL + "skills/spot.htm",
  'survival':                baseHelpURL + "skills/survival.htm",
  'swim':                    baseHelpURL + "skills/swim.htm",
  'tumble':                  baseHelpURL + "skills/tumble.htm",
  'use magic device':    baseHelpURL + "skills/useMagicDevice.htm",
  'use rope':                baseHelpURL + "skills/useRope.htm",

  // Feats
  'acrobatic':                          baseHelpURL + 'feats.htm#acrobatic',
  'agile':                             baseHelpURL + 'feats.htm#agile',
  'alertness':                          baseHelpURL + 'feats.htm#alertness',
  'animal affinity':                  baseHelpURL + 'feats.htm#animalAffinity',
  'armor proficiency (heavy)':     baseHelpURL + 'feats.htm#armorProficiencyHeavy',
  'armor proficiency (light)':     baseHelpURL + 'feats.htm#armorProficiencyLight',
  'armor proficiency (medium)':    baseHelpURL + 'feats.htm#armorProficiencyMedium',
  'armor proficiency':             baseHelpURL + 'feats.htm#armorProficiencyLight',
  'athletic':                           baseHelpURL + 'feats.htm#athletic',
  'augment summoning':                baseHelpURL + 'feats.htm#augmentSummoning',
  'blind-fight':                     baseHelpURL + 'feats.htm#blindFight',
  'brew potion':                     baseHelpURL + 'feats.htm#brewPotion',
  'cleave':                            baseHelpURL + 'feats.htm#cleave',
  'combat casting':                   baseHelpURL + 'feats.htm#combatCasting',
  'combat expertise':                 baseHelpURL + 'feats.htm#combatExpertise',
  'combat reflexes':                  baseHelpURL + 'feats.htm#combatReflexes',
  'craft magic arms and armor':    baseHelpURL + 'feats.htm#craftMagicArmsAndArmor',
  'craft rod':                          baseHelpURL + 'feats.htm#craftRod',
  'craft staff':                     baseHelpURL + 'feats.htm#craftStaff',
  'craft wand':                      baseHelpURL + 'feats.htm#craftWand',
  'craft wondrous item':          baseHelpURL + 'feats.htm#craftWondrousItem',
  'deceitful':                          baseHelpURL + 'feats.htm#deceitful',
  'deflect arrows':                   baseHelpURL + 'feats.htm#deflectArrows',
  'deft hands':                      baseHelpURL + 'feats.htm#deftHands',
  'diehard':                        baseHelpURL + 'feats.htm#diehard',
  'diligent':                           baseHelpURL + 'feats.htm#diligent',
  'dodge':                             baseHelpURL + 'feats.htm#dodge',
  'empower spell':                    baseHelpURL + 'feats.htm#empowerSpell',
  'endurance':                          baseHelpURL + 'feats.htm#endurance',
  'enlarge spell':                    baseHelpURL + 'feats.htm#enlargeSpell',
  'eschew materials':                 baseHelpURL + 'feats.htm#eschewMaterials',
  'exotic weapon proficiency':     baseHelpURL + 'feats.htm#exoticWeaponProficiency',
  'extend spell':                        baseHelpURL + 'feats.htm#extendSpell',
  'extra turning':                    baseHelpURL + 'feats.htm#extraTurning',
  'far shot':                           baseHelpURL + 'feats.htm#farShot',
  'forge ring':                      baseHelpURL + 'feats.htm#forgeRing',
  'great cleave':                        baseHelpURL + 'feats.htm#greatCleave',
  'great fortitude':                  baseHelpURL + 'feats.htm#greatFortitude',
  'greater spell focus':          baseHelpURL + 'feats.htm#greaterSpellFocus',
  'greater spell penetration':     baseHelpURL + 'feats.htm#greaterSpellPenetration',
  'greater two-weapon fighting':   baseHelpURL + 'feats.htm#greaterTwoWeaponFighting',
  'greater weapon focus':             baseHelpURL + 'feats.htm#greaterWeaponFocus',
  'greater weapon specialization': baseHelpURL + 'feats.htm#greaterWeaponSpecialization',
  'heighten spell':                   baseHelpURL + 'feats.htm#heightenSpell',
  'improved bull rush':               baseHelpURL + 'feats.htm#improvedBullRush',
  'improved counterspell':            baseHelpURL + 'feats.htm#improvedCounterspell',
  'improved critical':                baseHelpURL + 'feats.htm#improvedCritical',
  'improved disarm':                  baseHelpURL + 'feats.htm#improvedDisarm',
  'improved familiar':                baseHelpURL + 'feats.htm#improvedFamiliar',
  'improved feint':                   baseHelpURL + 'feats.htm#improvedFeint',
  'improved grapple':                 baseHelpURL + 'feats.htm#improvedGrapple',
  'improved initiative':          baseHelpURL + 'feats.htm#improvedInitiative',
  'improved overrun':                 baseHelpURL + 'feats.htm#improvedOverrun',
  'improved precise shot':            baseHelpURL + 'feats.htm#improvedPreciseShot',
  'improved shield bash':             baseHelpURL + 'feats.htm#improvedShieldBash',
  'improved sunder':                  baseHelpURL + 'feats.htm#improvedSunder',
  'improved trip':                    baseHelpURL + 'feats.htm#improvedTrip',
  'improved turning':                 baseHelpURL + 'feats.htm#improvedTurning',
  'improved two-weapon fighting':  baseHelpURL + 'feats.htm#improvedTwoWeaponFighting',
  'improved unarmed strike':      baseHelpURL + 'feats.htm#improvedUnarmedStrike',
  'investigator':                        baseHelpURL + 'feats.htm#investigator',
  'iron will':                          baseHelpURL + 'feats.htm#ironWill',
  'leadership':                      baseHelpURL + 'feats.htm#leadership',
  'lightning reflexes':               baseHelpURL + 'feats.htm#lightningReflexes',
  'magical aptitude':                 baseHelpURL + 'feats.htm#magicalAptitude',
  'manyshot':                           baseHelpURL + 'feats.htm#manyshot',
  'martial weapon proficiency':    baseHelpURL + 'feats.htm#martialWeaponProficiency',
  'maximize spell':                   baseHelpURL + 'feats.htm#maximizeSpell',
  'mobility':                           baseHelpURL + 'feats.htm#mobility',
  'mounted archery':                  baseHelpURL + 'feats.htm#mountedArchery',
  'mounted combat':                   baseHelpURL + 'feats.htm#mountedCombat',
  'natural spell':                    baseHelpURL + 'feats.htm#naturalSpell',
  'negotiator':                      baseHelpURL + 'feats.htm#negotiator',
  'nimble fingers':                   baseHelpURL + 'feats.htm#nimbleFingers',
  'persuasive':                      baseHelpURL + 'feats.htm#persuasive',
  'point blank shot':                 baseHelpURL + 'feats.htm#pointBlankShot',
  'power attack':                        baseHelpURL + 'feats.htm#powerAttack',
  'precise shot':                        baseHelpURL + 'feats.htm#preciseShot',
  'quick draw':                      baseHelpURL + 'feats.htm#quickDraw',
  'quicken spell':                    baseHelpURL + 'feats.htm#quickenSpell',
  'rapid reload':                        baseHelpURL + 'feats.htm#rapidReload',
  'rapid shot':                      baseHelpURL + 'feats.htm#rapidShot',
  'ride-by attack':                   baseHelpURL + 'feats.htm#rideByAttack',
  'run':                              baseHelpURL + 'feats.htm#run',
  'scribe scroll':                    baseHelpURL + 'feats.htm#scribeScroll',
  'self-sufficient':                  baseHelpURL + 'feats.htm#selfSufficient',
  'shield proficiency':               baseHelpURL + 'feats.htm#shieldProficiency',
  'shot on the run':                  baseHelpURL + 'feats.htm#shotOnTheRun',
  'silent spell':                        baseHelpURL + 'feats.htm#silentSpell',
  'simple weapon proficiency':     baseHelpURL + 'feats.htm#simpleWeaponProficiency',
  'skill focus':                     baseHelpURL + 'feats.htm#skillFocus',
  'snatch arrows':                    baseHelpURL + 'feats.htm#snatchArrows',
  'spell focus':                     baseHelpURL + 'feats.htm#spellFocus',
  'spell mastery':                    baseHelpURL + 'feats.htm#spellMasterySpecial',
  'spell penetration':                baseHelpURL + 'feats.htm#spellPenetration',
  'spirited charge':                  baseHelpURL + 'feats.htm#spiritedCharge',
  'spring attack':                    baseHelpURL + 'feats.htm#springAttack',
  'stealthy':                           baseHelpURL + 'feats.htm#stealthy',
  'still spell':                     baseHelpURL + 'feats.htm#stillSpell',
  'stunning fist':                    baseHelpURL + 'feats.htm#stunningFist',
  'toughness':                          baseHelpURL + 'feats.htm#toughness',
  'tower shield proficiency':         baseHelpURL + 'feats.htm#towerShieldProficiency',
  'track':                             baseHelpURL + 'feats.htm#track',
  'trample':                        baseHelpURL + 'feats.htm#trample',
  'two-weapon defense':               baseHelpURL + 'feats.htm#twoWeaponDefense',
  'two-weapon fighting':          baseHelpURL + 'feats.htm#twoWeaponFighting',
  'weapon finesse':                   baseHelpURL + 'feats.htm#weaponFinesse',
  'weapon focus':                        baseHelpURL + 'feats.htm#weaponFocus',
  'weapon specialization':            baseHelpURL + 'feats.htm#weaponSpecialization',
  'whirlwind attack':                 baseHelpURL + 'feats.htm#whirlwindAttack',
  'widen spell':                     baseHelpURL + 'feats.htm#widenSpell',

  // craft skill must come after craft feats for everything to get the right URLs.
  'craft':                   baseHelpURL + "skills/craft.htm",

  // Abilities
  'ability damage':          baseHelpURL + "naturalSpecialAbilities.htm#abilityDamage",
  'ability drain':           baseHelpURL + "naturalSpecialAbilities.htm#abilityDrain",
  'ability score loss':      baseHelpURL + "naturalSpecialAbilities.htm#abilityScoreLoss",
  'alternate form':          baseHelpURL + "naturalSpecialAbilities.htm#alternateForm",
  'antimagic':               baseHelpURL + "naturalSpecialAbilities.htm#antimagic",
  'bite':                    baseHelpURL + "naturalSpecialAbilities.htm#bite",
  'blindsense':              baseHelpURL + "naturalSpecialAbilities.htm#blindsightAndBlindsense",
  'blindsight':              baseHelpURL + "naturalSpecialAbilities.htm#blindsightAndBlindsense",
  'breath weapon':           baseHelpURL + "naturalSpecialAbilities.htm#breathWeapon",
  'burrow':                  baseHelpURL + "naturalSpecialAbilities.htm#burrow",
  'change shape':            baseHelpURL + "naturalSpecialAbilities.htm#changeShape",
  'charm':                   baseHelpURL + "naturalSpecialAbilities.htm#charmAndCompulsion",
  'claw':                    baseHelpURL + "naturalSpecialAbilities.htm#claworTalon",
  'climb':                   baseHelpURL + "naturalSpecialAbilities.htm#climb",
  'cold immunity':           baseHelpURL + "naturalSpecialAbilities.htm#coldImmunity",
  'compulsion':              baseHelpURL + "naturalSpecialAbilities.htm#charmAndCompulsion",
  'constrict':               baseHelpURL + "naturalSpecialAbilities.htm#constrict",
  'damage reduction':        baseHelpURL + "naturalSpecialAbilities.htm#damageReduction",
  'darkvision':              baseHelpURL + "naturalSpecialAbilities.htm#darkvision",
  'death attacks':           baseHelpURL + "naturalSpecialAbilities.htm#deathAttacks",
  'disease':                 baseHelpURL + "naturalSpecialAbilities.htm#disease",
  'energy drain':            baseHelpURL + "naturalSpecialAbilities.htm#energyDrainAndNegativeLevels",
  'etherealness':            baseHelpURL + "naturalSpecialAbilities.htm#etherealness",
  'evasion':                 baseHelpURL + "naturalSpecialAbilities.htm#evasionAndImprovedEvasion",
  'fast healing':            baseHelpURL + "naturalSpecialAbilities.htm#fastHealing",
  'fear aura':               baseHelpURL + "naturalSpecialAbilities.htm#fearAura",
  'fear cones':              baseHelpURL + "naturalSpecialAbilities.htm#fearConesSpandRays",
  'fear rays':               baseHelpURL + "naturalSpecialAbilities.htm#fearConesSpandRays",
  'fear':                    baseHelpURL + "naturalSpecialAbilities.htm#fear",
  'fire immunity':           baseHelpURL + "naturalSpecialAbilities.htm#fireImmunity",
  'fly':                     baseHelpURL + "naturalSpecialAbilities.htm#fly",
  'frightful presence':      baseHelpURL + "naturalSpecialAbilities.htm#frightfulPresence",
  'gaseous form':            baseHelpURL + "naturalSpecialAbilities.htm#gaseousForm",
  'gaze attacks':            baseHelpURL + "naturalSpecialAbilities.htm#gazeAttacks",
  'gore':                    baseHelpURL + "naturalSpecialAbilities.htm#gore",
  'improved evasion':        baseHelpURL + "naturalSpecialAbilities.htm#evasionAndImprovedEvasion",
  'improved grab':           baseHelpURL + "naturalSpecialAbilities.htm#improvedGrab",
  'incorporeality':          baseHelpURL + "naturalSpecialAbilities.htm#incorporeality",
  'invisibility':            baseHelpURL + "naturalSpecialAbilities.htm#invisibility",
  'level loss':              baseHelpURL + "naturalSpecialAbilities.htm#levelLoss",
  'low-light vision':        baseHelpURL + "naturalSpecialAbilities.htm#lowLightVision",
  'manufactured weapons':    baseHelpURL + "naturalSpecialAbilities.htm#manufacturedWeapons",
  'movement modes':          baseHelpURL + "naturalSpecialAbilities.htm#movementModes",
  'natural weapons':         baseHelpURL + "naturalSpecialAbilities.htm#naturalWeapons",
  'negative levels':         baseHelpURL + "naturalSpecialAbilities.htm#energyDrainAndNegativeLevels",
  'nonabilities':            baseHelpURL + "naturalSpecialAbilities.htm#nonabilities",
  'paralysis':               baseHelpURL + "naturalSpecialAbilities.htm#paralysis",
  'poison':                  baseHelpURL + "naturalSpecialAbilities.htm#poison",
  'polymorph':               baseHelpURL + "naturalSpecialAbilities.htm#polymorph",
  'pounce':                  baseHelpURL + "naturalSpecialAbilities.htm#pounce",
  'powerful charge':         baseHelpURL + "naturalSpecialAbilities.htm#powerfulCharge",
  'psionics':                baseHelpURL + "naturalSpecialAbilities.htm#psionics",
  'rake':                    baseHelpURL + "naturalSpecialAbilities.htm#rake",
  'rays':                    baseHelpURL + "naturalSpecialAbilities.htm#rays",
  'regeneration':            baseHelpURL + "naturalSpecialAbilities.htm#regeneration",
  'resistance to energy':    baseHelpURL + "naturalSpecialAbilities.htm#resistanceToEnergy",
  'scent':                   baseHelpURL + "naturalSpecialAbilities.htm#scent",
  'slam':                    baseHelpURL + "naturalSpecialAbilities.htm#slaporSlam",
  'slap':                    baseHelpURL + "naturalSpecialAbilities.htm#slaporSlam",
  'sonic attacks':           baseHelpURL + "naturalSpecialAbilities.htm#sonicAttacks",
  'spell immunity':          baseHelpURL + "naturalSpecialAbilities.htm#spellImmunity",
  'spell resistance':        baseHelpURL + "naturalSpecialAbilities.htm#spellResistance",
  'spells':                  baseHelpURL + "naturalSpecialAbilities.htm#spells",
  'sting':                   baseHelpURL + "naturalSpecialAbilities.htm#sting",
  'summon':                  baseHelpURL + "naturalSpecialAbilities.htm#summon",
  'swallow whole':           baseHelpURL + "naturalSpecialAbilities.htm#swallowWhole",
  'swim':                    baseHelpURL + "naturalSpecialAbilities.htm#swim",
  'talon':                   baseHelpURL + "naturalSpecialAbilities.htm#claworTalon",
  'telepathy':               baseHelpURL + "naturalSpecialAbilities.htm#telepathy",
  'tentacle':                baseHelpURL + "naturalSpecialAbilities.htm#tentacle",
  'trample':                 baseHelpURL + "naturalSpecialAbilities.htm#trample",
  'tremorsense':             baseHelpURL + "naturalSpecialAbilities.htm#tremorsense",
  'turn resistance':         baseHelpURL + "naturalSpecialAbilities.htm#turnResistance",
  'vulnerability to energy': baseHelpURL + "naturalSpecialAbilities.htm#vulnerabilitytoEnergy",

  // Druid special abilities.
  'animal companion' :        baseHelpURL + "classes/druid.htm#animalCompanion",
  'wild empathy'     :        baseHelpURL + "classes/druid.htm#wildEmpathy",
  'woodland stride'  :       baseHelpURL + "classes/druid.htm#woodlandStride",
  'nature sense'     :        baseHelpURL + "classes/druid.htm#natureSense",
  'trackless step'   :        baseHelpURL + "classes/druid.htm#tracklessStep",
  "resist nature's lure":    baseHelpURL + "classes/druid.htm#resistNaturesLure",
  'wild shape'       :       baseHelpURL + "classes/druid.htm#wildShape",
  'venom immunity'   :       baseHelpURL + "classes/druid.htm#venomImmunity",
  'a thousand faces' :       baseHelpURL + "classes/druid.htm#aThousandFaces",
  'timeless body'    :       baseHelpURL + "classes/druid.htm#druidTimelessBody",

  // Animal companion abilities.
  'link'             :       baseHelpURL + "classes/druid.htm#link",
  'share spells'     :       baseHelpURL + "classes/druid.htm#shareSpells",
  'devotion'         :       baseHelpURL + "classes/druid.htm#devotion",
  'multiattack'      :       baseHelpURL + "classes/druid.htm#multiattack",

  // Ranger special abilities.
  'wild empathy'     :        baseHelpURL + "classes/ranger.htm#wildEmpathy",
  'favored enemy'    :        baseHelpURL + "classes/ranger.htm#favoredEnemy",
  'combat style'     :        baseHelpURL + "classes/ranger.htm#combatStyle",
  'animal companion' :        baseHelpURL + "classes/druid.htm#animalCompanion",
  'improved combat style':   baseHelpURL + "classes/ranger.htm#improvedCombatStyle",
  'woodland stride'  :       baseHelpURL + "classes/ranger.htm#woodlandStride",
  'swift tracker'    :       baseHelpURL + "classes/ranger.htm#swiftTracker",
  'combat style mastery':    baseHelpURL + "classes/ranger.htm#combatStyleMastery",
  'camouflage'       :       baseHelpURL + "classes/ranger.htm#camouflage",
  'hide in plain sight':     baseHelpURL + "classes/ranger.htm#hideinPlainSight",

  // Rogue special abilities.
  'sneak attack'     :        baseHelpURL + "classes/rogue.htm#sneakAttack",
  'trapfinding'      :        baseHelpURL + "classes/rogue.htm#trapfinding",
  'trap sense'       :        baseHelpURL + "classes/rogue.htm#trapSense",
  'uncanny dodge'    :        baseHelpURL + "classes/rogue.htm#uncannyDodge",
  'improved uncanny dodge':  baseHelpURL + "classes/rogue.htm#improvedUncannyDodge",

  // Wizard special abilities.
  'summon familiar'  :        baseHelpURL + "classes/sorcererWizard.htm#wizardFamiliar",
  'scribe scroll'    :        baseHelpURL + "classes/sorcererWizard.htm#scribeScroll",

  '###last one###'   :           ""
};


var spellsHelpURL = {
  // Spells
  "acid arrow":                              baseHelpURL + "spells/acidArrow.htm",
  "acid fog":                                baseHelpURL + "spells/acidFog.htm",
  "acid splash":                             baseHelpURL + "spells/acidSplash.htm",
  "aid":                                     baseHelpURL + "spells/aid.htm",
  "air walk":                                baseHelpURL + "spells/airWalk.htm",
  "alarm":                                   baseHelpURL + "spells/alarm.htm",
  "align weapon":                        baseHelpURL + "spells/alignWeapon.htm",
  "alter self":                              baseHelpURL + "spells/alterSelf.htm",
  "analyze dweomer":                     baseHelpURL + "spells/analyzeDweomer.htm",
  "animal growth":                       baseHelpURL + "spells/animalGrowth.htm",
  "animal messenger":                    baseHelpURL + "spells/animalMessenger.htm",
  "animal shapes":                       baseHelpURL + "spells/animalShapes.htm",
  "animal trance":                       baseHelpURL + "spells/animalTrance.htm",
  "animate dead":                        baseHelpURL + "spells/animateDead.htm",
  "animate objects":                     baseHelpURL + "spells/animateObjects.htm",
  "animate plants":                          baseHelpURL + "spells/animatePlants.htm",
  "animate rope":                        baseHelpURL + "spells/animateRope.htm",
  "antilife shell":                          baseHelpURL + "spells/antilifeShell.htm",
  "antimagic field":                     baseHelpURL + "spells/antimagicField.htm",
  "antipathy":                           baseHelpURL + "spells/antipathy.htm",
  "antiplant shell":                     baseHelpURL + "spells/antiplantShell.htm",
  "arcane eye":                              baseHelpURL + "spells/arcaneEye.htm",
  "arcane lock":                             baseHelpURL + "spells/arcaneLock.htm",
  "arcane mark":                             baseHelpURL + "spells/arcaneMark.htm",
  "arcane sight":                        baseHelpURL + "spells/arcaneSight.htm",
  "arcane sight, greater":           baseHelpURL + "spells/arcaneSightGreater.htm",
  "astral projection":                   baseHelpURL + "spells/astralProjection.htm",
  "atonement":                           baseHelpURL + "spells/atonement.htm",
  "augury":                                  baseHelpURL + "spells/augury.htm",
  "awaken":                                  baseHelpURL + "spells/awaken.htm",
  "baleful polymorph":                   baseHelpURL + "spells/balefulPolymorph.htm",
  "bane":                                    baseHelpURL + "spells/bane.htm",
  "banishment":                              baseHelpURL + "spells/banishment.htm",
  "barkskin":                                baseHelpURL + "spells/barkskin.htm",
  "bear's endurance":                    baseHelpURL + "spells/bearsEndurance.htm",
  "bear's endurance, mass":              baseHelpURL + "spells/bearsEnduranceMass.htm",
  "bestow curse":                        baseHelpURL + "spells/bestowCurse.htm",
  "binding":                                 baseHelpURL + "spells/binding.htm",
  "black tentacles":                     baseHelpURL + "spells/blackTentacles.htm",
  "blade barrier":                       baseHelpURL + "spells/bladeBarrier.htm",
  "blasphemy":                           baseHelpURL + "spells/blasphemy.htm",
  "bless":                                   baseHelpURL + "spells/bless.htm",
  "bless water":                             baseHelpURL + "spells/blessWater.htm",
  "bless weapon":                        baseHelpURL + "spells/blessWeapon.htm",
  "blight":                                  baseHelpURL + "spells/blight.htm",
  "blindness/deafness":                  baseHelpURL + "spells/blindnessDeafness.htm",
  "blink":                                   baseHelpURL + "spells/blink.htm",
  "blur":                                    baseHelpURL + "spells/blur.htm",
  "break enchantment":                   baseHelpURL + "spells/breakEnchantment.htm",
  "bull's strength":                     baseHelpURL + "spells/bullsStrength.htm",
  "bull's strength, mass":           baseHelpURL + "spells/bullsStrengthMass.htm",
  "burning hands":                       baseHelpURL + "spells/burningHands.htm",
  "call lightning":                          baseHelpURL + "spells/callLightning.htm",
  "call lightning storm":                baseHelpURL + "spells/callLightningStorm.htm",
  "calm animals":                        baseHelpURL + "spells/calmAnimals.htm",
  "calm emotions":                       baseHelpURL + "spells/calmEmotions.htm",
  "cat's grace":                             baseHelpURL + "spells/catsGrace.htm",
  "cat's grace, mass":                   baseHelpURL + "spells/catsGraceMass.htm",
  "cause fear":                              baseHelpURL + "spells/causeFear.htm",
  "chain lightning":                     baseHelpURL + "spells/chainLightning.htm",
  "changestaff":                             baseHelpURL + "spells/changestaff.htm",
  "chaos hammer":                        baseHelpURL + "spells/chaosHammer.htm",
  "charm animal":                        baseHelpURL + "spells/charmAnimal.htm",
  "charm monster":                       baseHelpURL + "spells/charmMonster.htm",
  "charm monster, mass":                 baseHelpURL + "spells/charmMonsterMass.htm",
  "charm person":                        baseHelpURL + "spells/charmPerson.htm",
  "chill metal":                             baseHelpURL + "spells/chillMetal.htm",
  "chill touch":                             baseHelpURL + "spells/chillTouch.htm",
  "circle of death":                     baseHelpURL + "spells/circleofDeath.htm",
  "clairaudience/clairvoyance":          baseHelpURL + "spells/clairaudienceClairvoyance.htm",
  "clenched fist":                       baseHelpURL + "spells/clenchedFist.htm",
  "cloak of chaos":                          baseHelpURL + "spells/cloakofChaos.htm",
  "clone":                                   baseHelpURL + "spells/clone.htm",
  "cloudkill":                           baseHelpURL + "spells/cloudkill.htm",
  "color spray":                             baseHelpURL + "spells/colorSpray.htm",
  "command":                                 baseHelpURL + "spells/command.htm",
  "command, greater":                    baseHelpURL + "spells/commandGreater.htm",
  "command plants":                          baseHelpURL + "spells/commandPlants.htm",
  "command undead":                          baseHelpURL + "spells/commandUndead.htm",
  "commune":                                 baseHelpURL + "spells/commune.htm",
  "commune with nature":                 baseHelpURL + "spells/communewithNature.htm",
  "comprehend languages":                baseHelpURL + "spells/comprehendLanguages.htm",
  "cone of cold":                        baseHelpURL + "spells/coneofCold.htm",
  "confusion":                           baseHelpURL + "spells/confusion.htm",
  "confusion, lesser":                   baseHelpURL + "spells/confusionLesser.htm",
  "consecrate":                              baseHelpURL + "spells/consecrate.htm",
  "contact other plane":                 baseHelpURL + "spells/contactOtherPlane.htm",
  "contagion":                           baseHelpURL + "spells/contagion.htm",
  "contingency":                             baseHelpURL + "spells/contingency.htm",
  "continual flame":                     baseHelpURL + "spells/continualFlame.htm",
  "control plants":                          baseHelpURL + "spells/controlPlants.htm",
  "control undead":                          baseHelpURL + "spells/controlUndead.htm",
  "control water":                       baseHelpURL + "spells/controlWater.htm",
  "control weather":                     baseHelpURL + "spells/controlWeather.htm",
  "control winds":                       baseHelpURL + "spells/controlWinds.htm",
  "create food and water":           baseHelpURL + "spells/createFoodandWater.htm",
  "create greater undead":           baseHelpURL + "spells/createGreaterUndead.htm",
  "create undead":                       baseHelpURL + "spells/createUndead.htm",
  "create water":                        baseHelpURL + "spells/createWater.htm",
  "creeping doom":                       baseHelpURL + "spells/creepingDoom.htm",
  "crushing despair":                    baseHelpURL + "spells/crushingDespair.htm",
  "crushing hand":                       baseHelpURL + "spells/crushingHand.htm",
  "cure critical wounds":                baseHelpURL + "spells/cureCriticalWounds.htm",
  "cure critical wounds, mass":          baseHelpURL + "spells/cureCriticalWoundsMass.htm",
  "cure light wounds":                   baseHelpURL + "spells/cureLightWounds.htm",
  "cure light wounds, mass":             baseHelpURL + "spells/cureLightWoundsMass.htm",
  "cure minor wounds":                   baseHelpURL + "spells/cureMinorWounds.htm",
  "cure moderate wounds":                baseHelpURL + "spells/cureModerateWounds.htm",
  "cure moderate wounds, mass":          baseHelpURL + "spells/cureModerateWoundsMass.htm",
  "cure serious wounds":                 baseHelpURL + "spells/cureSeriousWounds.htm",
  "cure serious wounds, mass":       baseHelpURL + "spells/cureSeriousWoundsMass.htm",
  "curse water":                             baseHelpURL + "spells/curseWater.htm",
  "dancing lights":                          baseHelpURL + "spells/dancingLights.htm",
  "darkness":                                baseHelpURL + "spells/darkness.htm",
  "darkvision":                              baseHelpURL + "spells/darkvision.htm",
  "daylight":                                baseHelpURL + "spells/daylight.htm",
  "daze":                                    baseHelpURL + "spells/daze.htm",
  "daze monster":                        baseHelpURL + "spells/dazeMonster.htm",
  "death knell":                             baseHelpURL + "spells/deathKnell.htm",
  "death ward":                              baseHelpURL + "spells/deathWard.htm",
  "deathwatch":                              baseHelpURL + "spells/deathwatch.htm",
  "deep slumber":                        baseHelpURL + "spells/deepSlumber.htm",
  "deeper darkness":                     baseHelpURL + "spells/deeperDarkness.htm",
  "delay poison":                        baseHelpURL + "spells/delayPoison.htm",
  "delayed blast fireball":              baseHelpURL + "spells/delayedBlastFireball.htm",
  "demand":                                  baseHelpURL + "spells/demand.htm",
  "desecrate":                           baseHelpURL + "spells/desecrate.htm",
  "destruction":                             baseHelpURL + "spells/destruction.htm",
  "detect animals or plants":        baseHelpURL + "spells/detectAnimalsorPlants.htm",
  "detect chaos":                        baseHelpURL + "spells/detectChaos.htm",
  "detect evil":                             baseHelpURL + "spells/detectEvil.htm",
  "detect good":                             baseHelpURL + "spells/detectGood.htm",
  "detect law":                              baseHelpURL + "spells/detectLaw.htm",
  "detect magic":                        baseHelpURL + "spells/detectMagic.htm",
  "detect poison":                       baseHelpURL + "spells/detectPoison.htm",
  "detect scrying":                          baseHelpURL + "spells/detectScrying.htm",
  "detect secret doors":                 baseHelpURL + "spells/detectSecretDoors.htm",
  "detect snares and pits":              baseHelpURL + "spells/detectSnaresandPits.htm",
  "detect thoughts":                     baseHelpURL + "spells/detectThoughts.htm",
  "detect undead":                       baseHelpURL + "spells/detectUndead.htm",
  "dictum":                                  baseHelpURL + "spells/dictum.htm",
  "dimension door":                          baseHelpURL + "spells/dimensionDoor.htm",
  "dimensional anchor":                  baseHelpURL + "spells/dimensionalAnchor.htm",
  "dimensional lock":                    baseHelpURL + "spells/dimensionalLock.htm",
  "diminish plants":                     baseHelpURL + "spells/diminishPlants.htm",
  "discern lies":                        baseHelpURL + "spells/discernLies.htm",
  "discern location":                    baseHelpURL + "spells/discernLocation.htm",
  "disguise self":                       baseHelpURL + "spells/disguiseSelf.htm",
  "disintegrate":                        baseHelpURL + "spells/disintegrate.htm",
  "dismissal":                           baseHelpURL + "spells/dismissal.htm",
  "dispel chaos":                        baseHelpURL + "spells/dispelChaos.htm",
  "dispel evil":                             baseHelpURL + "spells/dispelEvil.htm",
  "dispel good":                             baseHelpURL + "spells/dispelGood.htm",
  "dispel law":                              baseHelpURL + "spells/dispelLaw.htm",
  "dispel magic":                        baseHelpURL + "spells/dispelMagic.htm",
  "dispel magic, greater":           baseHelpURL + "spells/dispelMagicGreater.htm",
  "displacement":                        baseHelpURL + "spells/displacement.htm",
  "disrupt undead":                          baseHelpURL + "spells/disruptUndead.htm",
  "disrupting weapon":                   baseHelpURL + "spells/disruptingWeapon.htm",
  "divination":                              baseHelpURL + "spells/divination.htm",
  "divine favor":                        baseHelpURL + "spells/divineFavor.htm",
  "divine power":                        baseHelpURL + "spells/divinePower.htm",
  "dominate animal":                     baseHelpURL + "spells/dominateAnimal.htm",
  "dominate monster":                    baseHelpURL + "spells/dominateMonster.htm",
  "dominate person":                     baseHelpURL + "spells/dominatePerson.htm",
  "doom":                                    baseHelpURL + "spells/doom.htm",
  "dream":                                   baseHelpURL + "spells/dream.htm",
  "eagle's splendor":                    baseHelpURL + "spells/eaglesSplendor.htm",
  "eagle's splendor, mass":              baseHelpURL + "spells/eaglesSplendorMass.htm",
  "earthquake":                              baseHelpURL + "spells/earthquake.htm",
  "elemental swarm":                     baseHelpURL + "spells/elementalSwarm.htm",
  "endure elements":                     baseHelpURL + "spells/endureElements.htm",
  "energy drain":                        baseHelpURL + "spells/energyDrain.htm",
  "enervation":                              baseHelpURL + "spells/enervation.htm",
  "enlarge person":                          baseHelpURL + "spells/enlargePerson.htm",
  "enlarge person, mass":                baseHelpURL + "spells/enlargePersonMass.htm",
  "entangle":                                baseHelpURL + "spells/entangle.htm",
  "enthrall":                                baseHelpURL + "spells/enthrall.htm",
  "entropic shield":                     baseHelpURL + "spells/entropicShield.htm",
  "erase":                                   baseHelpURL + "spells/erase.htm",
  "ethereal jaunt":                          baseHelpURL + "spells/etherealJaunt.htm",
  "etherealness":                        baseHelpURL + "spells/etherealness.htm",
  "expeditious retreat":                 baseHelpURL + "spells/expeditiousRetreat.htm",
  "explosive runes":                     baseHelpURL + "spells/explosiveRunes.htm",
  "eyebite":                                 baseHelpURL + "spells/eyebite.htm",
  "fabricate":                           baseHelpURL + "spells/fabricate.htm",
  "faerie fire":                             baseHelpURL + "spells/faerieFire.htm",
  "false life":                              baseHelpURL + "spells/falseLife.htm",
  "false vision":                        baseHelpURL + "spells/falseVision.htm",
  "fear":                                    baseHelpURL + "spells/fear.htm",
  "feather fall":                        baseHelpURL + "spells/featherFall.htm",
  "feeblemind":                              baseHelpURL + "spells/feeblemind.htm",
  "find the path":                       baseHelpURL + "spells/findthePath.htm",
  "find traps":                              baseHelpURL + "spells/findTraps.htm",
  "finger of death":                     baseHelpURL + "spells/fingerofDeath.htm",
  "fire seeds":                              baseHelpURL + "spells/fireSeeds.htm",
  "fire shield":                             baseHelpURL + "spells/fireShield.htm",
  "fire storm":                              baseHelpURL + "spells/fireStorm.htm",
  "fire trap":                           baseHelpURL + "spells/fireTrap.htm",
  "fireball":                                baseHelpURL + "spells/fireball.htm",
  "flame arrow":                             baseHelpURL + "spells/flameArrow.htm",
  "flame blade":                             baseHelpURL + "spells/flameBlade.htm",
  "flame strike":                        baseHelpURL + "spells/flameStrike.htm",
  "flaming sphere":                          baseHelpURL + "spells/flamingSphere.htm",
  "flare":                                   baseHelpURL + "spells/flare.htm",
  "flesh to stone":                          baseHelpURL + "spells/fleshtoStone.htm",
  "fly":                                     baseHelpURL + "spells/fly.htm",
  "floating disk":                       baseHelpURL + "spells/floatingDisk.htm",
  "fog cloud":                           baseHelpURL + "spells/fogCloud.htm",
  "forbiddance":                             baseHelpURL + "spells/forbiddance.htm",
  "forcecage":                           baseHelpURL + "spells/forcecage.htm",
  "forceful hand":                       baseHelpURL + "spells/forcefulHand.htm",
  "foresight":                           baseHelpURL + "spells/foresight.htm",
  "fox's cunning":                       baseHelpURL + "spells/foxsCunning.htm",
  "fox's cunning, mass":                 baseHelpURL + "spells/foxsCunningMass.htm",
  "freedom":                                 baseHelpURL + "spells/freedom.htm",
  "freedom of movement":                 baseHelpURL + "spells/freedomofMovement.htm",
  "freezing sphere":                     baseHelpURL + "spells/freezingSphere.htm",
  "gaseous form":                        baseHelpURL + "spells/gaseousForm.htm",
  "gate":                                    baseHelpURL + "spells/gate.htm",
  "geas/quest":                              baseHelpURL + "spells/geasQuest.htm",
  "geas, lesser":                        baseHelpURL + "spells/geasLesser.htm",
  "gentle repose":                       baseHelpURL + "spells/gentleRepose.htm",
  "ghost sound":                             baseHelpURL + "spells/ghostSound.htm",
  "ghoul touch":                             baseHelpURL + "spells/ghoulTouch.htm",
  "giant vermin":                        baseHelpURL + "spells/giantVermin.htm",
  "glibness":                                baseHelpURL + "spells/glibness.htm",
  "glitterdust":                             baseHelpURL + "spells/glitterdust.htm",
  "globe of invulnerability":        baseHelpURL + "spells/globeofInvulnerability.htm",
  "globe of invulnerability, lesser": baseHelpURL + "spells/globeofInvulnerabilityLesser.htm",
  "glyph of warding":                    baseHelpURL + "spells/glyphofWarding.htm",
  "glyph of warding, greater":       baseHelpURL + "spells/glyphofWardingGreater.htm",
  "goodberry":                           baseHelpURL + "spells/goodberry.htm",
  "good hope":                           baseHelpURL + "spells/goodHope.htm",
  "grasping hand":                       baseHelpURL + "spells/graspingHand.htm",
  "grease":                                  baseHelpURL + "spells/grease.htm",
  "greater (spell name)":                baseHelpURL + "spells/greaterSpellName.htm",
  "guards and wards":                    baseHelpURL + "spells/guardsandWards.htm",
  "guidance":                                baseHelpURL + "spells/guidance.htm",
  "gust of wind":                        baseHelpURL + "spells/gustofWind.htm",
  "hallow":                                  baseHelpURL + "spells/hallow.htm",
  "hallucinatory terrain":           baseHelpURL + "spells/hallucinatoryTerrain.htm",
  "halt undead":                             baseHelpURL + "spells/haltUndead.htm",
  "harm":                                    baseHelpURL + "spells/harm.htm",
  "haste":                                   baseHelpURL + "spells/haste.htm",
  "heal":                                    baseHelpURL + "spells/heal.htm",
  "heal, mass":                              baseHelpURL + "spells/healMass.htm",
  "heal mount":                              baseHelpURL + "spells/healMount.htm",
  "heat metal":                              baseHelpURL + "spells/heatMetal.htm",
  "helping hand":                        baseHelpURL + "spells/helpingHand.htm",
  "heroes' feast":                       baseHelpURL + "spells/heroesFeast.htm",
  "heroism":                                 baseHelpURL + "spells/heroism.htm",
  "heroism, greater":                    baseHelpURL + "spells/heroismGreater.htm",
  "hide from animals":                   baseHelpURL + "spells/hidefromAnimals.htm",
  "hide from undead":                    baseHelpURL + "spells/hidefromUndead.htm",
  "hideous laughter":                    baseHelpURL + "spells/hideousLaughter.htm",
  "hold animal":                             baseHelpURL + "spells/holdAnimal.htm",
  "hold monster":                        baseHelpURL + "spells/holdMonster.htm",
  "hold monster, mass":                  baseHelpURL + "spells/holdMonsterMass.htm",
  "hold person":                             baseHelpURL + "spells/holdPerson.htm",
  "hold person, mass":                   baseHelpURL + "spells/holdPersonMass.htm",
  "hold portal":                             baseHelpURL + "spells/holdPortal.htm",
  "holy aura":                           baseHelpURL + "spells/holyAura.htm",
  "holy smite":                              baseHelpURL + "spells/holySmite.htm",
  "holy sword":                              baseHelpURL + "spells/holySword.htm",
  "holy word":                           baseHelpURL + "spells/holyWord.htm",
  "horrid wilting":                          baseHelpURL + "spells/horridWilting.htm",
  "hypnotic pattern":                    baseHelpURL + "spells/hypnoticPattern.htm",
  "hypnotism":                           baseHelpURL + "spells/hypnotism.htm",
  "ice storm":                           baseHelpURL + "spells/iceStorm.htm",
  "identify":                                baseHelpURL + "spells/identify.htm",
  "illusory script":                     baseHelpURL + "spells/illusoryScript.htm",
  "illusory wall":                       baseHelpURL + "spells/illusoryWall.htm",
  "imbue with spell ability":        baseHelpURL + "spells/imbuewithSpellAbility.htm",
  "implosion":                           baseHelpURL + "spells/implosion.htm",
  "imprisonment":                        baseHelpURL + "spells/imprisonment.htm",
  "incendiary cloud":                    baseHelpURL + "spells/incendiaryCloud.htm",
  "inflict critical wounds":             baseHelpURL + "spells/inflictCriticalWounds.htm",
  "inflict critical wounds, mass":    baseHelpURL + "spells/inflictCriticalWoundsMass.htm",
  "inflict light wounds":                baseHelpURL + "spells/inflictLightWounds.htm",
  "inflict light wounds, mass":          baseHelpURL + "spells/inflictLightWoundsMass.htm",
  "inflict minor wounds":                baseHelpURL + "spells/inflictMinorWounds.htm",
  "inflict moderate wounds":             baseHelpURL + "spells/inflictModerateWounds.htm",
  "inflict moderate wounds, mass":    baseHelpURL + "spells/inflictModerateWoundsMass.htm",
  "inflict serious wounds":              baseHelpURL + "spells/inflictSeriousWounds.htm",
  "inflict serious wounds, mass":     baseHelpURL + "spells/inflictSeriousWoundsMass.htm",
  "insanity":                                baseHelpURL + "spells/insanity.htm",
  "insect plague":                       baseHelpURL + "spells/insectPlague.htm",
  "instant summons":                     baseHelpURL + "spells/instantSummons.htm",
  "interposing hand":                    baseHelpURL + "spells/interposingHand.htm",
  "invisibility":                        baseHelpURL + "spells/invisibility.htm",
  "invisibility, greater":           baseHelpURL + "spells/invisibilityGreater.htm",
  "invisibility, mass":                  baseHelpURL + "spells/invisibilityMass.htm",
  "invisibility purge":                  baseHelpURL + "spells/invisibilityPurge.htm",
  "invisibility sphere":                 baseHelpURL + "spells/invisibilitySphere.htm",
  "iron body":                           baseHelpURL + "spells/ironBody.htm",
  "ironwood":                                baseHelpURL + "spells/ironwood.htm",
  "irresistible dance":                  baseHelpURL + "spells/irresistibleDance.htm",
  "jump":                                    baseHelpURL + "spells/jump.htm",
  "keen edge":                           baseHelpURL + "spells/keenEdge.htm",
  "knock":                                   baseHelpURL + "spells/knock.htm",
  "know direction":                          baseHelpURL + "spells/knowDirection.htm",
  "legend lore":                             baseHelpURL + "spells/legendLore.htm",
  "lesser (spell name)":                 baseHelpURL + "spells/lesserSpellName.htm",
  "levitate":                                baseHelpURL + "spells/levitate.htm",
  "light":                                   baseHelpURL + "spells/light.htm",
  "lightning bolt":                          baseHelpURL + "spells/lightningBolt.htm",
  "limited wish":                        baseHelpURL + "spells/limitedWish.htm",
  "liveoak":                                 baseHelpURL + "spells/liveoak.htm",
  "locate creature":                     baseHelpURL + "spells/locateCreature.htm",
  "locate object":                       baseHelpURL + "spells/locateObject.htm",
  "longstrider":                             baseHelpURL + "spells/longstrider.htm",
  "lullaby":                                 baseHelpURL + "spells/lullaby.htm",
  "mage armor":                              baseHelpURL + "spells/mageArmor.htm",
  "mage hand":                           baseHelpURL + "spells/mageHand.htm",
  "mage's disjunction":                  baseHelpURL + "spells/magesDisjunction.htm",
  "mage's faithful hound":           baseHelpURL + "spells/magesFaithfulHound.htm",
  "mage's lucubration":                  baseHelpURL + "spells/magesLucubration.htm",
  "mage's magnificent mansion":          baseHelpURL + "spells/magesMagnificentMansion.htm",
  "mage's private sanctum":              baseHelpURL + "spells/magesPrivateSanctum.htm",
  "mage's sword":                        baseHelpURL + "spells/magesSword.htm",
  "magic aura":                              baseHelpURL + "spells/magicAura.htm",
  "magic circle against chaos":          baseHelpURL + "spells/magicCircleagainstChaos.htm",
  "magic circle against evil":       baseHelpURL + "spells/magicCircleagainstEvil.htm",
  "magic circle against good":       baseHelpURL + "spells/magicCircleagainstGood.htm",
  "magic circle against law":        baseHelpURL + "spells/magicCircleagainstLaw.htm",
  "magic fang":                              baseHelpURL + "spells/magicFang.htm",
  "magic fang, greater":                 baseHelpURL + "spells/magicFangGreater.htm",
  "magic jar":                           baseHelpURL + "spells/magicJar.htm",
  "magic missile":                       baseHelpURL + "spells/magicMissile.htm",
  "magic mouth":                             baseHelpURL + "spells/magicMouth.htm",
  "magic stone":                             baseHelpURL + "spells/magicStone.htm",
  "magic vestment":                          baseHelpURL + "spells/magicVestment.htm",
  "magic weapon":                        baseHelpURL + "spells/magicWeapon.htm",
  "magic weapon, greater":           baseHelpURL + "spells/magicWeaponGreater.htm",
  "major creation":                          baseHelpURL + "spells/majorCreation.htm",
  "major image":                             baseHelpURL + "spells/majorImage.htm",
  "make whole":                              baseHelpURL + "spells/makeWhole.htm",
  "mark of justice":                     baseHelpURL + "spells/markofJustice.htm",
  "mass (spell name)":                   baseHelpURL + "spells/massSpellName.htm",
  "maze":                                    baseHelpURL + "spells/maze.htm",
  "meld into stone":                     baseHelpURL + "spells/meldintoStone.htm",
  "mending":                                 baseHelpURL + "spells/mending.htm",
  "message":                                 baseHelpURL + "spells/message.htm",
  "meteor swarm":                        baseHelpURL + "spells/meteorSwarm.htm",
  "mind blank":                              baseHelpURL + "spells/mindBlank.htm",
  "mind fog":                                baseHelpURL + "spells/mindFog.htm",
  "minor creation":                          baseHelpURL + "spells/minorCreation.htm",
  "minor image":                             baseHelpURL + "spells/minorImage.htm",
  "miracle":                                 baseHelpURL + "spells/miracle.htm",
  "mirage arcana":                       baseHelpURL + "spells/mirageArcana.htm",
  "mirror image":                        baseHelpURL + "spells/mirrorImage.htm",
  "misdirection":                        baseHelpURL + "spells/misdirection.htm",
  "mislead":                                 baseHelpURL + "spells/mislead.htm",
  "mnemonic enhancer":                   baseHelpURL + "spells/mnemonicEnhancer.htm",
  "modify memory":                       baseHelpURL + "spells/modifyMemory.htm",
  "moment of prescience":                baseHelpURL + "spells/momentofPrescience.htm",
  "mount":                                   baseHelpURL + "spells/mount.htm",
  "move earth":                              baseHelpURL + "spells/moveEarth.htm",
  "neutralize poison":                   baseHelpURL + "spells/neutralizePoison.htm",
  "nightmare":                           baseHelpURL + "spells/nightmare.htm",
  "nondetection":                        baseHelpURL + "spells/nondetection.htm",
  "obscure object":                          baseHelpURL + "spells/obscureObject.htm",
  "obscuring mist":                          baseHelpURL + "spells/obscuringMist.htm",
  "open/close":                              baseHelpURL + "spells/openClose.htm",
  "order's wrath":                       baseHelpURL + "spells/ordersWrath.htm",
  "overland flight":                     baseHelpURL + "spells/overlandFlight.htm",
  "owl's wisdom":                        baseHelpURL + "spells/owlsWisdom.htm",
  "owl's wisdom, mass":                  baseHelpURL + "spells/owlsWisdomMass.htm",
  "passwall":                                baseHelpURL + "spells/passwall.htm",
  "pass without trace":                  baseHelpURL + "spells/passwithoutTrace.htm",
  "permanency":                              baseHelpURL + "spells/permanency.htm",
  "permanent image":                     baseHelpURL + "spells/permanentImage.htm",
  "persistent image":                    baseHelpURL + "spells/persistentImage.htm",
  "phantasmal killer":                   baseHelpURL + "spells/phantasmalKiller.htm",
  "phantom steed":                       baseHelpURL + "spells/phantomSteed.htm",
  "phantom trap":                        baseHelpURL + "spells/phantomTrap.htm",
  "phase door":                              baseHelpURL + "spells/phaseDoor.htm",
  "planar ally":                             baseHelpURL + "spells/planarAlly.htm",
  "planar ally, greater":                baseHelpURL + "spells/planarAllyGreater.htm",
  "planar ally, lesser":                 baseHelpURL + "spells/planarAllyLesser.htm",
  "planar binding":                          baseHelpURL + "spells/planarBinding.htm",
  "planar binding, greater":             baseHelpURL + "spells/planarBindingGreater.htm",
  "planar binding, lesser":              baseHelpURL + "spells/planarBindingLesser.htm",
  "plane shift":                             baseHelpURL + "spells/planeShift.htm",
  "plant growth":                        baseHelpURL + "spells/plantGrowth.htm",
  "poison":                                  baseHelpURL + "spells/poison.htm",
  "polar ray":                           baseHelpURL + "spells/polarRay.htm",
  "polymorph":                           baseHelpURL + "spells/polymorph.htm",
  "polymorph any object":                baseHelpURL + "spells/polymorphAnyObject.htm",
  "power word blind":                    baseHelpURL + "spells/powerWordBlind.htm",
  "power word kill":                     baseHelpURL + "spells/powerWordKill.htm",
  "power word stun":                     baseHelpURL + "spells/powerWordStun.htm",
  "prayer":                                  baseHelpURL + "spells/prayer.htm",
  "prestidigitation":                    baseHelpURL + "spells/prestidigitation.htm",
  "prismatic sphere":                    baseHelpURL + "spells/prismaticSphere.htm",
  "prismatic spray":                     baseHelpURL + "spells/prismaticSpray.htm",
  "prismatic wall":                          baseHelpURL + "spells/prismaticWall.htm",
  "produce flame":                       baseHelpURL + "spells/produceFlame.htm",
  "programmed image":                    baseHelpURL + "spells/programmedImage.htm",
  "project image":                       baseHelpURL + "spells/projectImage.htm",
  "protection from arrows":              baseHelpURL + "spells/protectionfromArrows.htm",
  "protection from chaos":           baseHelpURL + "spells/protectionfromChaos.htm",
  "protection from energy":              baseHelpURL + "spells/protectionfromEnergy.htm",
  "protection from evil":                baseHelpURL + "spells/protectionfromEvil.htm",
  "protection from good":                baseHelpURL + "spells/protectionfromGood.htm",
  "protection from law":                 baseHelpURL + "spells/protectionfromLaw.htm",
  "protection from spells":              baseHelpURL + "spells/protectionfromSpells.htm",
  "prying eyes":                             baseHelpURL + "spells/pryingEyes.htm",
  "prying eyes, greater":                baseHelpURL + "spells/pryingEyesGreater.htm",
  "purify food and drink":           baseHelpURL + "spells/purifyFoodandDrink.htm",
  "pyrotechnics":                        baseHelpURL + "spells/pyrotechnics.htm",
  "quench":                                  baseHelpURL + "spells/quench.htm",
  "rage":                                    baseHelpURL + "spells/rage.htm",
  "rainbow pattern":                     baseHelpURL + "spells/rainbowPattern.htm",
  "raise dead":                              baseHelpURL + "spells/raiseDead.htm",
  "ray of enfeeblement":                 baseHelpURL + "spells/rayofEnfeeblement.htm",
  "ray of exhaustion":                   baseHelpURL + "spells/rayofExhaustion.htm",
  "ray of frost":                        baseHelpURL + "spells/rayofFrost.htm",
  "read magic":                              baseHelpURL + "spells/readMagic.htm",
  "reduce animal":                       baseHelpURL + "spells/reduceAnimal.htm",
  "reduce person":                       baseHelpURL + "spells/reducePerson.htm",
  "reduce person, mass":                 baseHelpURL + "spells/reducePersonMass.htm",
  "refuge":                                  baseHelpURL + "spells/refuge.htm",
  "regenerate":                              baseHelpURL + "spells/regenerate.htm",
  "reincarnate":                             baseHelpURL + "spells/reincarnate.htm",
  "remove blindness/deafness":       baseHelpURL + "spells/removeBlindnessDeafness.htm",
  "remove curse":                        baseHelpURL + "spells/removeCurse.htm",
  "remove disease":                          baseHelpURL + "spells/removeDisease.htm",
  "remove fear":                             baseHelpURL + "spells/removeFear.htm",
  "remove paralysis":                    baseHelpURL + "spells/removeParalysis.htm",
  "repel metal or stone":                baseHelpURL + "spells/repelMetalorStone.htm",
  "repel vermin":                        baseHelpURL + "spells/repelVermin.htm",
  "repel wood":                              baseHelpURL + "spells/repelWood.htm",
  "repulsion":                           baseHelpURL + "spells/repulsion.htm",
  "resilient sphere":                    baseHelpURL + "spells/resilientSphere.htm",
  "resistance":                              baseHelpURL + "spells/resistance.htm",
  "resist energy":                       baseHelpURL + "spells/resistEnergy.htm",
  "restoration":                             baseHelpURL + "spells/restoration.htm",
  "restoration, greater":                baseHelpURL + "spells/restorationGreater.htm",
  "restoration, lesser":                 baseHelpURL + "spells/restorationLesser.htm",
  "resurrection":                        baseHelpURL + "spells/resurrection.htm",
  "reverse gravity":                     baseHelpURL + "spells/reverseGravity.htm",
  "righteous might":                     baseHelpURL + "spells/righteousMight.htm",
  "rope trick":                              baseHelpURL + "spells/ropeTrick.htm",
  "rusting grasp":                       baseHelpURL + "spells/rustingGrasp.htm",
  "sanctuary":                           baseHelpURL + "spells/sanctuary.htm",
  "scare":                                   baseHelpURL + "spells/scare.htm",
  "scintillating pattern":           baseHelpURL + "spells/scintillatingPattern.htm",
  "scorching ray":                       baseHelpURL + "spells/scorchingRay.htm",
  "screen":                                  baseHelpURL + "spells/screen.htm",
  "scrying":                                 baseHelpURL + "spells/scrying.htm",
  "scrying, greater":                    baseHelpURL + "spells/scryingGreater.htm",
  "sculpt sound":                        baseHelpURL + "spells/sculptSound.htm",
  "searing light":                       baseHelpURL + "spells/searingLight.htm",
  "secret chest":                        baseHelpURL + "spells/secretChest.htm",
  "secret page":                             baseHelpURL + "spells/secretPage.htm",
  "secure shelter":                          baseHelpURL + "spells/secureShelter.htm",
  "see invisibility":                    baseHelpURL + "spells/seeInvisibility.htm",
  "seeming":                                 baseHelpURL + "spells/seeming.htm",
  "sending":                                 baseHelpURL + "spells/sending.htm",
  "sepia snake sigil":                   baseHelpURL + "spells/sepiaSnakeSigil.htm",
  "sequester":                           baseHelpURL + "spells/sequester.htm",
  "shades":                                  baseHelpURL + "spells/shades.htm",
  "shadow conjuration":                  baseHelpURL + "spells/shadowConjuration.htm",
  "shadow conjuration, greater":      baseHelpURL + "spells/shadowConjurationGreater.htm",
  "shadow evocation":                    baseHelpURL + "spells/shadowEvocation.htm",
  "shadow evocation, greater":       baseHelpURL + "spells/shadowEvocationGreater.htm",
  "shadow walk":                             baseHelpURL + "spells/shadowWalk.htm",
  "shambler":                                baseHelpURL + "spells/shambler.htm",
  "shapechange":                             baseHelpURL + "spells/shapechange.htm",
  "shatter":                                 baseHelpURL + "spells/shatter.htm",
  "shield":                                  baseHelpURL + "spells/shield.htm",
  "shield of faith":                     baseHelpURL + "spells/shieldofFaith.htm",
  "shield of law":                       baseHelpURL + "spells/shieldofLaw.htm",
  "shield other":                        baseHelpURL + "spells/shieldOther.htm",
  "shillelagh":                              baseHelpURL + "spells/shillelagh.htm",
  "shocking grasp":                          baseHelpURL + "spells/shockingGrasp.htm",
  "shout":                                   baseHelpURL + "spells/shout.htm",
  "shout, greater":                          baseHelpURL + "spells/shoutGreater.htm",
  "shrink item":                             baseHelpURL + "spells/shrinkItem.htm",
  "silence":                                 baseHelpURL + "spells/silence.htm",
  "silent image":                        baseHelpURL + "spells/silentImage.htm",
  "simulacrum":                              baseHelpURL + "spells/simulacrum.htm",
  "slay living":                             baseHelpURL + "spells/slayLiving.htm",
  "sleep":                                   baseHelpURL + "spells/sleep.htm",
  "sleet storm":                             baseHelpURL + "spells/sleetStorm.htm",
  "slow":                                    baseHelpURL + "spells/slow.htm",
  "snare":                                   baseHelpURL + "spells/snare.htm",
  "soften earth and stone":              baseHelpURL + "spells/softenEarthandStone.htm",
  "solid fog":                           baseHelpURL + "spells/solidFog.htm",
  "song of discord":                     baseHelpURL + "spells/songofDiscord.htm",
  "soul bind":                           baseHelpURL + "spells/soulBind.htm",
  "sound burst":                             baseHelpURL + "spells/soundBurst.htm",
  "speak with animals":                  baseHelpURL + "spells/speakwithAnimals.htm",
  "speak with dead":                     baseHelpURL + "spells/speakwithDead.htm",
  "speak with plants":                   baseHelpURL + "spells/speakwithPlants.htm",
  "spectral hand":                       baseHelpURL + "spells/spectralHand.htm",
  "spell immunity":                          baseHelpURL + "spells/spellImmunity.htm",
  "spell immunity, greater":             baseHelpURL + "spells/spellImmunityGreater.htm",
  "spell resistance":                    baseHelpURL + "spells/spellResistance.htm",
  "spellstaff":                              baseHelpURL + "spells/spellstaff.htm",
  "spell turning":                       baseHelpURL + "spells/spellTurning.htm",
  "spider climb":                        baseHelpURL + "spells/spiderClimb.htm",
  "spike growth":                        baseHelpURL + "spells/spikeGrowth.htm",
  "spike stones":                        baseHelpURL + "spells/spikeStones.htm",
  "spiritual weapon":                    baseHelpURL + "spells/spiritualWeapon.htm",
  "statue":                                  baseHelpURL + "spells/statue.htm",
  "status":                                  baseHelpURL + "spells/status.htm",
  "stinking cloud":                          baseHelpURL + "spells/stinkingCloud.htm",
  "stone shape":                             baseHelpURL + "spells/stoneShape.htm",
  "stoneskin":                           baseHelpURL + "spells/stoneskin.htm",
  "stone tell":                              baseHelpURL + "spells/stoneTell.htm",
  "stone to flesh":                          baseHelpURL + "spells/stonetoFlesh.htm",
  "storm of vengeance":                  baseHelpURL + "spells/stormofVengeance.htm",
  "suggestion":                              baseHelpURL + "spells/suggestion.htm",
  "suggestion, mass":                    baseHelpURL + "spells/suggestionMass.htm",
  "summon instrument":                   baseHelpURL + "spells/summonInstrument.htm",
  "summon monster i":                    baseHelpURL + "spells/summonMonsterI.htm",
  "summon monster ii":                   baseHelpURL + "spells/summonMonsterII.htm",
  "summon monster iii":                  baseHelpURL + "spells/summonMonsterIII.htm",
  "summon monster iv":                   baseHelpURL + "spells/summonMonsterIV.htm",
  "summon monster v":                    baseHelpURL + "spells/summonMonsterV.htm",
  "summon monster vi":                   baseHelpURL + "spells/summonMonsterVI.htm",
  "summon monster vii":                  baseHelpURL + "spells/summonMonsterVII.htm",
  "summon monster viii":                 baseHelpURL + "spells/summonMonsterVIII.htm",
  "summon monster ix":                   baseHelpURL + "spells/summonMonsterIX.htm",
  "summon nature's ally i":              baseHelpURL + "spells/summonNaturesAllyI.htm",
  "summon nature's ally ii":             baseHelpURL + "spells/summonNaturesAllyII.htm",
  "summon nature's ally iii":        baseHelpURL + "spells/summonNaturesAllyIII.htm",
  "summon nature's ally iv":             baseHelpURL + "spells/summonNaturesAllyIV.htm",
  "summon nature's ally v":              baseHelpURL + "spells/summonNaturesAllyV.htm",
  "summon nature's ally vi":             baseHelpURL + "spells/summonNaturesAllyVI.htm",
  "summon nature's ally vii":        baseHelpURL + "spells/summonNaturesAllyVII.htm",
  "summon nature's ally viii":       baseHelpURL + "spells/summonNaturesAllyVIII.htm",
  "summon nature's ally ix":             baseHelpURL + "spells/summonNaturesAllyIX.htm",
  "summon swarm":                        baseHelpURL + "spells/summonSwarm.htm",
  "sunbeam":                                 baseHelpURL + "spells/sunbeam.htm",
  "sunburst":                                baseHelpURL + "spells/sunburst.htm",
  "symbol of death":                     baseHelpURL + "spells/symbolofDeath.htm",
  "symbol of fear":                          baseHelpURL + "spells/symbolofFear.htm",
  "symbol of insanity":                  baseHelpURL + "spells/symbolofInsanity.htm",
  "symbol of pain":                          baseHelpURL + "spells/symbolofPain.htm",
  "symbol of persuasion":                baseHelpURL + "spells/symbolofPersuasion.htm",
  "symbol of sleep":                     baseHelpURL + "spells/symbolofSleep.htm",
  "symbol of stunning":                  baseHelpURL + "spells/symbolofStunning.htm",
  "symbol of weakness":                  baseHelpURL + "spells/symbolofWeakness.htm",
  "sympathetic vibration":           baseHelpURL + "spells/sympatheticVibration.htm",
  "sympathy":                                baseHelpURL + "spells/sympathy.htm",
  "telekinesis":                             baseHelpURL + "spells/telekinesis.htm",
  "telekinetic sphere":                  baseHelpURL + "spells/telekineticSphere.htm",
  "telepathic bond":                     baseHelpURL + "spells/telepathicBond.htm",
  "teleport":                                baseHelpURL + "spells/teleport.htm",
  "teleport object":                     baseHelpURL + "spells/teleportObject.htm",
  "teleport, greater":                   baseHelpURL + "spells/teleportGreater.htm",
  "teleportation circle":                baseHelpURL + "spells/teleportationCircle.htm",
  "temporal stasis":                     baseHelpURL + "spells/temporalStasis.htm",
  "time stop":                           baseHelpURL + "spells/timeStop.htm",
  "tiny hut":                                baseHelpURL + "spells/tinyHut.htm",
  "tongues":                                 baseHelpURL + "spells/tongues.htm",
  "touch of fatigue":                    baseHelpURL + "spells/touchofFatigue.htm",
  "touch of idiocy":                     baseHelpURL + "spells/touchofIdiocy.htm",
  "transformation":                          baseHelpURL + "spells/transformation.htm",
  "transmute metal to wood":             baseHelpURL + "spells/transmuteMetaltoWood.htm",
  "transmute mud to rock":           baseHelpURL + "spells/transmuteMudtoRock.htm",
  "transmute rock to mud":           baseHelpURL + "spells/transmuteRocktoMud.htm",
  "transport via plants":                baseHelpURL + "spells/transportviaPlants.htm",
  "trap the soul":                       baseHelpURL + "spells/traptheSoul.htm",
  "tree shape":                              baseHelpURL + "spells/treeShape.htm",
  "tree stride":                             baseHelpURL + "spells/treeStride.htm",
  "true resurrection":                   baseHelpURL + "spells/trueResurrection.htm",
  "true seeing":                             baseHelpURL + "spells/trueSeeing.htm",
  "true strike":                             baseHelpURL + "spells/trueStrike.htm",
  "undeath to death":                    baseHelpURL + "spells/undeathtoDeath.htm",
  "undetectable alignment":              baseHelpURL + "spells/undetectableAlignment.htm",
  "unhallow":                                baseHelpURL + "spells/unhallow.htm",
  "unholy aura":                             baseHelpURL + "spells/unholyAura.htm",
  "unholy blight":                       baseHelpURL + "spells/unholyBlight.htm",
  "unseen servant":                          baseHelpURL + "spells/unseenServant.htm",
  "vampiric touch":                          baseHelpURL + "spells/vampiricTouch.htm",
  "veil":                                    baseHelpURL + "spells/veil.htm",
  "ventriloquism":                       baseHelpURL + "spells/ventriloquism.htm",
  "virtue":                                  baseHelpURL + "spells/virtue.htm",
  "vision":                                  baseHelpURL + "spells/vision.htm",
  "wail of the banshee":                 baseHelpURL + "spells/wailoftheBanshee.htm",
  "wall of fire":                        baseHelpURL + "spells/wallofFire.htm",
  "wall of force":                       baseHelpURL + "spells/wallofForce.htm",
  "wall of ice":                             baseHelpURL + "spells/wallofIce.htm",
  "wall of iron":                        baseHelpURL + "spells/wallofIron.htm",
  "wall of stone":                       baseHelpURL + "spells/wallofStone.htm",
  "wall of thorns":                          baseHelpURL + "spells/wallofThorns.htm",
  "warp wood":                           baseHelpURL + "spells/warpWood.htm",
  "water breathing":                     baseHelpURL + "spells/waterBreathing.htm",
  "water walk":                              baseHelpURL + "spells/waterWalk.htm",
  "waves of exhaustion":                 baseHelpURL + "spells/wavesofExhaustion.htm",
  "waves of fatigue":                    baseHelpURL + "spells/wavesofFatigue.htm",
  "web":                                     baseHelpURL + "spells/web.htm",
  "weird":                                   baseHelpURL + "spells/weird.htm",
  "whirlwind":                           baseHelpURL + "spells/whirlwind.htm",
  "whispering wind":                     baseHelpURL + "spells/whisperingWind.htm",
  "wind walk":                           baseHelpURL + "spells/windWalk.htm",
  "wind wall":                           baseHelpURL + "spells/windWall.htm",
  "wish":                                    baseHelpURL + "spells/wish.htm",
  "wood shape":                              baseHelpURL + "spells/woodShape.htm",
  "word of chaos":                       baseHelpURL + "spells/wordofChaos.htm",
  "word of recall":                          baseHelpURL + "spells/wordofRecall.htm",
  "zone of silence":                     baseHelpURL + "spells/zoneofSilence.htm",
  "zone of truth":                       baseHelpURL + "spells/zoneofTruth.htm",


  '###last one###'   :           ""
};

